name: "Week 3: Docker Scan and Push"

on:
  push:
    branches:
      - main

jobs:
  scan-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Tag Docker Image
        run: |
          docker build -t nikesevojno/bloxicosava:latest .
          docker tag nikesevojno/bloxicosava:latest nikesevojno/bloxicosava:commit-${{ github.sha }}

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker push your-docker-hub-username/your-image-name:latest
          docker push your-docker-hub-username/your-image-name:commit-${{ github.sha }}

