name: week_2_assignment

on: 
  workflow_dispatch:

  push: 
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Echo 
      run: echo Hello GitHub Actions!
