name: 'Week 3: Scanning and pushing to Docker Hub'

on:
  push:

jobs:
  scan-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 

